In [138]:
import sys,os
__script_path=os.path.abspath(globals().get('__file__','.'))
__script_dir = os.path.dirname(__script_path)
root_dir = os.path.abspath(f'{__script_dir}/../../..')
print(root_dir)
for lib in [root_dir][::-1]:
    if lib in sys.path:
        sys.path.remove(lib)
    sys.path.insert(0,lib)

from libs.common import *
from config.config import *

c:\Users\Admin\Data\ads_fraud_detection

# 3. Tiền xử lí dữ liệu

In [139]:
save_dir=f"{exps_dir}/exp1/exp_gan"

save_dir = f"{save_dir}"
os.makedirs(save_dir, exist_ok=True)
test_size=0.33
seed=42

In [140]:
test_size=0.33
seed=42
data=pd.read_excel(f'{exps_dir}/exp1/data_EDA.xlsx')
data

    months_as_customer     age policy_state policy_csl  policy_deductable  policy_annual_premium  umbrella_limit insured_sex insured_education_level insured_occupation insured_hobbies insured_relationship  capital-gains  capital-loss             incident_type   collision_type incident_severity authorities_contacted incident_state incident_city incident_hour_of_the_day  number_of_vehicles_involved property_damage  bodily_injuries  witnesses police_report_available  total_claim_amount  injury_claim  property_claim  vehicle_claim   auto_make auto_model   auto_year fraud_reported  day_policy_bind_date  month_policy_bind_date  year_policy_bind_date  day_incident_date  month_incident_date  year_incident_date
0                    Y  Middle           OH    250/500               1000                1406.91               0        MALE                      MD       craft-repair        sleeping              husband          53300             0  Single Vehicle Collision   Side Collision      Major Damage                Police             SC      Columbus                  Morning                            1             YES                1          2                     YES               71610          6510           13020          52080        Saab        92x   2002-2008              Y                    17                      10                   2014                 25                    1                2015
1                    Y  Middle           IN    250/500               2000                1197.22         5000000        MALE                      MD  machine-op-inspct         reading       other-relative              0             0             Vehicle Theft                ?      Minor Damage                Police             VA     Riverwood                  Morning                            1               ?                0          0                       ?                5070           780             780           3510    Mercedes       E400   2002-2008              Y                    27                       6                   2006                 21                    1                2015
2                    Y   Young           OH    100/300               2000                1413.14         5000000      FEMALE                     PhD              sales     board-games            own-child          35100             0   Multi-vehicle Collision   Rear Collision      Minor Damage                Police             NY      Columbus                  Morning                            3              NO                2          3                      NO               34650          7700            3850          23100       Dodge        RAM   2002-2008              N                     6                       9                   2000                 22                    2                2015
3                    Y  Middle           IL    250/500               2000                1415.74         6000000      FEMALE                     PhD       armed-forces     board-games            unmarried          48900        -62400  Single Vehicle Collision  Front Collision      Major Damage                Police             OH     Arlington                  Morning                            1               ?                1          2                      NO               63400          6340            6340          50720   Chevrolet      Tahoe      2018++              Y                    25                       5                   1990                 10                    1                2015
4                    Y  Middle           IL   500/1000               1000                1583.91         6000000        MALE               Associate              sales     board-games            unmarried          66000        -46000             Vehicle Theft                ?      Minor Damage                   NaN             NY     Arlington                    Night                            1              NO                0          1                      NO                6500          1300             650           4550      Accura        RSX      2018++              N                     6                       6                   2014                 17                    2                2015
..                 ...     ...          ...        ...                ...                    ...             ...         ...                     ...                ...             ...                  ...            ...           ...                       ...              ...               ...                   ...            ...           ...                      ...                          ...             ...              ...        ...                     ...                 ...           ...             ...            ...         ...        ...         ...            ...                   ...                     ...                    ...                ...                  ...                 ...
995                  N  Middle           OH   500/1000               1000                1310.80               0      FEMALE                 Masters       craft-repair       paintball            unmarried              0             0  Single Vehicle Collision  Front Collision      Minor Damage                  Fire             NC    Northbrook                    Night                            1             YES                0          1                       ?               87200         17440            8720          61040       Honda     Accord   2002-2008              N                    16                       7                   1991                 22                    2                2015
996                  Y  Middle           IL    100/300               1000                1436.79               0      FEMALE                     PhD     prof-specialty        sleeping                 wife          70900             0  Single Vehicle Collision   Rear Collision      Major Damage                  Fire             SC     Northbend                    Night                            1             YES                2          3                       ?              108480         18080           18080          72320  Volkswagen     Passat      2018++              N                     5                       1                   2014                 24                    1                2015
997                  Y   Young           OH    250/500                500                1383.49         3000000      FEMALE                 Masters       armed-forces  bungie-jumping       other-relative          35100             0   Multi-vehicle Collision   Side Collision      Minor Damage                Police             NC     Arlington                  Morning                            3               ?                2          3                     YES               67500          7500            7500          52500      Suburu    Impreza  1995-20001              N                    17                       2                   2003                 23                    1                2015
998                  Y     Old           IL   500/1000               2000                1356.92         5000000        MALE               Associate  handlers-cleaners    base-jumping                 wife              0             0  Single Vehicle Collision   Rear Collision      Major Damage                 Other             NY     Arlington                  Morning                            1               ?                0          1                     YES               46980          5220            5220          36540        Audi         A5  1995-20001              N                    18                      11                   2011                 26                    2                2015
999                  Y     Old           OH    250/500               1000                 766.19               0      FEMALE               Associate              sales        kayaking              husband              0             0                Parked Car                ?      Minor Damage                Police             WV      Columbus                  Morning                            1               ?                0          3                       ?                5060           460             920           3680    Mercedes       E400   2002-2008              N                    11                      11                   1996                 26                    2                2015

[1000 rows x 40 columns]

In [141]:
data_train, data_test = train_test_split(data, test_size = 0.33, random_state=seed)
print(data_train.shape,data_test.shape)
data_train.to_excel(f'{save_dir}/datatrain.xlsx', index=None)
data_test.to_excel(f'{save_dir}/datatest.xlsx', index=None)

(670, 40) (330, 40)

In [142]:
data_train

    months_as_customer     age policy_state policy_csl  policy_deductable  policy_annual_premium  umbrella_limit insured_sex insured_education_level insured_occupation insured_hobbies insured_relationship  capital-gains  capital-loss             incident_type   collision_type incident_severity authorities_contacted incident_state incident_city incident_hour_of_the_day  number_of_vehicles_involved property_damage  bodily_injuries  witnesses police_report_available  total_claim_amount  injury_claim  property_claim  vehicle_claim auto_make  auto_model   auto_year fraud_reported  day_policy_bind_date  month_policy_bind_date  year_policy_bind_date  day_incident_date  month_incident_date  year_incident_date
703                  Y  Middle           IL    250/500               1000                 817.28               0        MALE             High School              sales       cross-fit            unmarried          62200             0   Multi-vehicle Collision   Rear Collision        Total Loss             Ambulance             SC      Columbus                  Evening                            3               ?                1          1                      NO               60190          4630            9260          46300  Mercedes       ML350      2018++              Y                    21                       6                   1994                  3                    1                2015
311                  N   Young           IN    100/300               2000                 765.64               0        MALE                      MD              sales    base-jumping        not-in-family              0        -22200   Multi-vehicle Collision  Front Collision      Major Damage             Ambulance             SC    Northbrook                  Morning                            3               ?                0          3                       ?               31350          2850            5700          22800     Honda      Accord  1995-20001              Y                    11                       6                   2008                 16                    2                2015
722                  Y  Middle           OH    100/300               2000                1422.21               0      FEMALE               Associate  handlers-cleaners            polo            unmarried              0        -46400  Single Vehicle Collision   Side Collision      Major Damage             Ambulance             WV     Riverwood                    Night                            1             YES                2          1                      NO               85900         17180           17180          51540    Suburu   Forrestor   2002-2008              Y                    29                       7                   1996                 16                    1                2015
629                  Y  Middle           IL    100/300               2000                1133.27               0      FEMALE             High School       craft-repair           chess                 wife              0        -56400   Multi-vehicle Collision   Side Collision        Total Loss                 Other             NY    Northbrook                    Night                            2               ?                0          2                     YES               60500         11000            5500          44000      Ford        F150  1995-20001              Y                    28                       5                   2014                  1                    3                2015
0                    Y  Middle           OH    250/500               1000                1406.91               0        MALE                      MD       craft-repair        sleeping              husband          53300             0  Single Vehicle Collision   Side Collision      Major Damage                Police             SC      Columbus                  Morning                            1             YES                1          2                     YES               71610          6510           13020          52080      Saab         92x   2002-2008              Y                    17                      10                   2014                 25                    1                2015
..                 ...     ...          ...        ...                ...                    ...             ...         ...                     ...                ...             ...                  ...            ...           ...                       ...              ...               ...                   ...            ...           ...                      ...                          ...             ...              ...        ...                     ...                 ...           ...             ...            ...       ...         ...         ...            ...                   ...                     ...                    ...                ...                  ...                 ...
106                  Y     Old           OH   500/1000               1000                1125.37               0      FEMALE               Associate     prof-specialty      basketball              husband              0        -56400   Multi-vehicle Collision   Rear Collision      Major Damage                Police             VA     Northbend                  Morning                            3               ?                0          2                     YES               79800          6650           19950          53200      Saab          95  1995-20001              Y                     7                      10                   1990                 13                    1                2015
270                  Y     Old           OH    250/500               2000                1589.54               0        MALE                 College  handlers-cleaners         camping              husband          55400             0   Multi-vehicle Collision   Rear Collision      Minor Damage                Police             VA     Arlington                  Morning                            3               ?                2          0                     YES               85300         17060            8530          59710    Toyota  Highlander   2002-2008              N                    15                       4                   2013                 27                    1                2015
860                  Y  Middle           IN    100/300               1000                1023.11               0      FEMALE                      MD       adm-clerical            golf            own-child              0        -45300   Multi-vehicle Collision   Rear Collision      Minor Damage                 Other             NY     Northbend                  Evening                            3              NO                1          2                     YES               58850         10700           10700          37450    Accura         MDX  1995-20001              N                    16                      11                   2004                  6                    2                2015
435                  N   Young           OH    250/500                500                1075.41               0        MALE                      MD  machine-op-inspct         reading                 wife          55200             0  Single Vehicle Collision   Side Collision        Total Loss                Police             PA     Northbend                  Morning                            1              NO                1          0                      NO               73400          7340            7340          58720     Dodge        Neon  1995-20001              N                    29                       8                   1999                 15                    2                2015
102                  Y  Middle           IL    250/500                500                1497.35               0      FEMALE                      JD     prof-specialty  bungie-jumping              husband          37300        -31700   Multi-vehicle Collision  Front Collision      Minor Damage                  Fire             NC    Northbrook                  Evening                            3               ?                2          3                      NO               28800             0            3600          25200      Ford      Fusion      2018++              N                     6                       6                   2001                 29                    1                2015

[670 rows x 40 columns]

In [143]:
# outliers_list=dict(np.load(f'{save_dir}/outliers.npz'))['outliers']
# def remove_outliers_iqr(data, column):
#     Q1 = data[column].quantile(0.25)
#     Q3 = data[column].quantile(0.75)
#     IQR = Q3 - Q1
#     lower_bound = Q1 - 1.5 * IQR
#     upper_bound = Q3 + 1.5 * IQR
#     return data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]

# # Áp dụng hàm cho các cột chứa dữ liệu cần loại bỏ ngoại lệ
# for column in outliers_list:
#     data_train = remove_outliers_iqr(data_train, column)
# data_train

In [144]:
data.isnull().sum()

months_as_customer              4
age                             2
policy_state                    0
policy_csl                      0
policy_deductable               0
policy_annual_premium           0
umbrella_limit                  0
insured_sex                     0
insured_education_level         0
insured_occupation              0
insured_hobbies                 0
insured_relationship            0
capital-gains                   0
capital-loss                    0
incident_type                   0
collision_type                  0
incident_severity               0
authorities_contacted          91
incident_state                  0
incident_city                   0
incident_hour_of_the_day       52
number_of_vehicles_involved     0
property_damage                 0
bodily_injuries                 0
witnesses                       0
police_report_available         0
total_claim_amount              0
injury_claim                    0
property_claim                  0
vehicle_claim                   0
auto_make                       0
auto_model                      0
auto_year                       0
fraud_reported                  0
day_policy_bind_date            0
month_policy_bind_date          0
year_policy_bind_date           0
day_incident_date               0
month_incident_date             0
year_incident_date              0
dtype: int64

In [145]:
data_train['collision_type']=data_train['collision_type'].replace('?',np.nan)
data_train['collision_type'].fillna(method='ffill',inplace=True)
data_train[['property_damage','police_report_available']]=data_train[['property_damage','police_report_available']].replace('?','Unknow')
(data_train=='?').sum()

months_as_customer             0
age                            0
policy_state                   0
policy_csl                     0
policy_deductable              0
policy_annual_premium          0
umbrella_limit                 0
insured_sex                    0
insured_education_level        0
insured_occupation             0
insured_hobbies                0
insured_relationship           0
capital-gains                  0
capital-loss                   0
incident_type                  0
collision_type                 0
incident_severity              0
authorities_contacted          0
incident_state                 0
incident_city                  0
incident_hour_of_the_day       0
number_of_vehicles_involved    0
property_damage                0
bodily_injuries                0
witnesses                      0
police_report_available        0
total_claim_amount             0
injury_claim                   0
property_claim                 0
vehicle_claim                  0
auto_make                      0
auto_model                     0
auto_year                      0
fraud_reported                 0
day_policy_bind_date           0
month_policy_bind_date         0
year_policy_bind_date          0
day_incident_date              0
month_incident_date            0
year_incident_date             0
dtype: int64

In [146]:
gen_y_train=data_train['fraud_reported' ]
label_encoder = LabelEncoder()
gen_y_train= label_encoder.fit_transform(gen_y_train)
gen_y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [147]:
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(data_train['fraud_reported']), y=data_train['fraud_reported'])
class_weights_dict = {i : class_weights[i] for i in range(len(class_weights))}
np.savez(f'{save_dir}/class_weights_dict.npz', class_weights_dict = class_weights_dict)
class_weights_dict

{0: 0.6555772994129159, 1: 2.106918238993711}

# 4.Chuẩn hóa dữ liệu

In [148]:
numeric_columns=dict(np.load(f'{exps_dir}/exp1/columns_dtype.npz',allow_pickle=True))['numeric_columns']
numeric_columns

array(['policy_annual_premium', 'capital-gains', 'capital-loss',
       'total_claim_amount', 'injury_claim', 'property_claim',
       'vehicle_claim', 'day_policy_bind_date', 'month_policy_bind_date',
       'year_policy_bind_date', 'day_incident_date',
       'month_incident_date', 'year_incident_date'], dtype='<U22')

In [149]:
category_columns=dict(np.load(f'{exps_dir}/exp1/columns_dtype.npz',allow_pickle=True))['category_columns']
category_columns

array(['months_as_customer', 'age', 'policy_state', 'policy_csl',
       'policy_deductable', 'umbrella_limit', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'incident_type', 'collision_type',
       'incident_severity', 'authorities_contacted', 'incident_state',
       'incident_city', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage',
       'bodily_injuries', 'witnesses', 'police_report_available',
       'auto_make', 'auto_model', 'auto_year', 'fraud_reported'],
      dtype='<U27')

In [150]:
data_train

    months_as_customer     age policy_state policy_csl  policy_deductable  policy_annual_premium  umbrella_limit insured_sex insured_education_level insured_occupation insured_hobbies insured_relationship  capital-gains  capital-loss             incident_type   collision_type incident_severity authorities_contacted incident_state incident_city incident_hour_of_the_day  number_of_vehicles_involved property_damage  bodily_injuries  witnesses police_report_available  total_claim_amount  injury_claim  property_claim  vehicle_claim auto_make  auto_model   auto_year fraud_reported  day_policy_bind_date  month_policy_bind_date  year_policy_bind_date  day_incident_date  month_incident_date  year_incident_date
703                  Y  Middle           IL    250/500               1000                 817.28               0        MALE             High School              sales       cross-fit            unmarried          62200             0   Multi-vehicle Collision   Rear Collision        Total Loss             Ambulance             SC      Columbus                  Evening                            3          Unknow                1          1                      NO               60190          4630            9260          46300  Mercedes       ML350      2018++              Y                    21                       6                   1994                  3                    1                2015
311                  N   Young           IN    100/300               2000                 765.64               0        MALE                      MD              sales    base-jumping        not-in-family              0        -22200   Multi-vehicle Collision  Front Collision      Major Damage             Ambulance             SC    Northbrook                  Morning                            3          Unknow                0          3                  Unknow               31350          2850            5700          22800     Honda      Accord  1995-20001              Y                    11                       6                   2008                 16                    2                2015
722                  Y  Middle           OH    100/300               2000                1422.21               0      FEMALE               Associate  handlers-cleaners            polo            unmarried              0        -46400  Single Vehicle Collision   Side Collision      Major Damage             Ambulance             WV     Riverwood                    Night                            1             YES                2          1                      NO               85900         17180           17180          51540    Suburu   Forrestor   2002-2008              Y                    29                       7                   1996                 16                    1                2015
629                  Y  Middle           IL    100/300               2000                1133.27               0      FEMALE             High School       craft-repair           chess                 wife              0        -56400   Multi-vehicle Collision   Side Collision        Total Loss                 Other             NY    Northbrook                    Night                            2          Unknow                0          2                     YES               60500         11000            5500          44000      Ford        F150  1995-20001              Y                    28                       5                   2014                  1                    3                2015
0                    Y  Middle           OH    250/500               1000                1406.91               0        MALE                      MD       craft-repair        sleeping              husband          53300             0  Single Vehicle Collision   Side Collision      Major Damage                Police             SC      Columbus                  Morning                            1             YES                1          2                     YES               71610          6510           13020          52080      Saab         92x   2002-2008              Y                    17                      10                   2014                 25                    1                2015
..                 ...     ...          ...        ...                ...                    ...             ...         ...                     ...                ...             ...                  ...            ...           ...                       ...              ...               ...                   ...            ...           ...                      ...                          ...             ...              ...        ...                     ...                 ...           ...             ...            ...       ...         ...         ...            ...                   ...                     ...                    ...                ...                  ...                 ...
106                  Y     Old           OH   500/1000               1000                1125.37               0      FEMALE               Associate     prof-specialty      basketball              husband              0        -56400   Multi-vehicle Collision   Rear Collision      Major Damage                Police             VA     Northbend                  Morning                            3          Unknow                0          2                     YES               79800          6650           19950          53200      Saab          95  1995-20001              Y                     7                      10                   1990                 13                    1                2015
270                  Y     Old           OH    250/500               2000                1589.54               0        MALE                 College  handlers-cleaners         camping              husband          55400             0   Multi-vehicle Collision   Rear Collision      Minor Damage                Police             VA     Arlington                  Morning                            3          Unknow                2          0                     YES               85300         17060            8530          59710    Toyota  Highlander   2002-2008              N                    15                       4                   2013                 27                    1                2015
860                  Y  Middle           IN    100/300               1000                1023.11               0      FEMALE                      MD       adm-clerical            golf            own-child              0        -45300   Multi-vehicle Collision   Rear Collision      Minor Damage                 Other             NY     Northbend                  Evening                            3              NO                1          2                     YES               58850         10700           10700          37450    Accura         MDX  1995-20001              N                    16                      11                   2004                  6                    2                2015
435                  N   Young           OH    250/500                500                1075.41               0        MALE                      MD  machine-op-inspct         reading                 wife          55200             0  Single Vehicle Collision   Side Collision        Total Loss                Police             PA     Northbend                  Morning                            1              NO                1          0                      NO               73400          7340            7340          58720     Dodge        Neon  1995-20001              N                    29                       8                   1999                 15                    2                2015
102                  Y  Middle           IL    250/500                500                1497.35               0      FEMALE                      JD     prof-specialty  bungie-jumping              husband          37300        -31700   Multi-vehicle Collision  Front Collision      Minor Damage                  Fire             NC    Northbrook                  Evening                            3          Unknow                2          3                      NO               28800             0            3600          25200      Ford      Fusion      2018++              N                     6                       6                   2001                 29                    1                2015

[670 rows x 40 columns]

In [151]:
# import pandas as pd
# from sklearn.preprocessing import OneHotEncoder

# # Giả sử bạn đã có một DataFrame tên là data_train và các cột phân loại
# data_train = pd.DataFrame({
#     'loai_xe': ['SUV', 'sedan', 'SUV', 'hatchback'],
#     'mau_sac': ['red', 'blue', 'green', 'blue'],
#     'gia': [20000, 15000, 22000, 18000]
# })

# # Các cột phân loại
# category_columns = ['loai_xe', 'mau_sac']

# label_encoders = {}

# for column in category_columns:
#     encoder = OneHotEncoder(sparse_output=False)
    
#     # Chuyển đổi cột thành 2D và thực hiện One-Hot Encoding
#     encoded = encoder.fit_transform(data_train[[column]])  # Nhớ rằng phải truyền DataFrame 2D
    
#     # Chuyển kết quả One-Hot Encoding thành DataFrame với cùng chỉ số
#     encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out([column]), index=data_train.index)
    
#     # Bỏ cột gốc và thêm các cột đã được One-Hot Encoding vào data_train
#     data_train = pd.concat([data_train.drop(column, axis=1), encoded_df], axis=1)
    
#     # Lưu encoder để có thể sử dụng lại sau này
#     label_encoders[column] = encoder

# print(data_train)

In [152]:
data_train['collision_type']=data_train['collision_type'].replace('?',np.nan)
data_train['collision_type'].fillna(method='ffill',inplace=True)
data_train[['property_damage','police_report_available']]=data_train[['property_damage','police_report_available']].replace('?','Unknow')
(data_train=='?').sum()

months_as_customer             0
age                            0
policy_state                   0
policy_csl                     0
policy_deductable              0
policy_annual_premium          0
umbrella_limit                 0
insured_sex                    0
insured_education_level        0
insured_occupation             0
insured_hobbies                0
insured_relationship           0
capital-gains                  0
capital-loss                   0
incident_type                  0
collision_type                 0
incident_severity              0
authorities_contacted          0
incident_state                 0
incident_city                  0
incident_hour_of_the_day       0
number_of_vehicles_involved    0
property_damage                0
bodily_injuries                0
witnesses                      0
police_report_available        0
total_claim_amount             0
injury_claim                   0
property_claim                 0
vehicle_claim                  0
auto_make                      0
auto_model                     0
auto_year                      0
fraud_reported                 0
day_policy_bind_date           0
month_policy_bind_date         0
year_policy_bind_date          0
day_incident_date              0
month_incident_date            0
year_incident_date             0
dtype: int64

In [153]:
label_encoders = {}
for column in category_columns:
    label_encoder = LabelEncoder()
    data_train[column] = label_encoder.fit_transform(data_train[column])
    label_encoders[column] = label_encoder  # Lưu trữ label encoder nếu cần sau này

scaler = StandardScaler()
data_train[numeric_columns] = scaler.fit_transform(data_train[numeric_columns])
data_train

     months_as_customer  age  policy_state  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  insured_sex  insured_education_level  insured_occupation  insured_hobbies  insured_relationship  capital-gains  capital-loss  incident_type  collision_type  incident_severity  authorities_contacted  incident_state  incident_city  incident_hour_of_the_day  number_of_vehicles_involved  property_damage  bodily_injuries  witnesses  police_report_available  total_claim_amount  injury_claim  property_claim  vehicle_claim  auto_make  auto_model  auto_year  fraud_reported  day_policy_bind_date  month_policy_bind_date  year_policy_bind_date  day_incident_date  month_incident_date  year_incident_date
703                   1    0             0           1                  1              -1.770734               0            1                        2                  11                6                     4       1.270697      0.970481              0               1                  2                      0               4              1                         0                            2                1                1          1                        0            0.249230     -0.612776        0.358110       0.416329          8          24          2               1              0.579574               -0.179439              -1.020460          -1.393943            -0.947412                 0.0
311                   0    2             1           0                  2              -1.979562               0            1                        4                  11                0                     1      -0.919382      0.175400              0               0                  0                      0               4              4                         1                            2                1                0          3                        1           -0.845210     -0.976821       -0.374783      -0.834115          6           6          0               1             -0.547936               -0.179439               0.908584           0.115223             0.953085                 0.0
722                   1    0             2           0                  2               0.675544               0            0                        0                   5               14                     4      -0.919382     -0.691310              2               2                  0                      0               6              5                         2                            0                2                2          1                        0            1.224890      1.953951        1.988592       0.695152         11          15          1               1              1.481582                0.108179              -0.744883           0.115223            -0.947412                 0.0
629                   1    0             0           0                  2              -0.492901               0            0                        2                   2                5                     5      -0.919382     -1.049454              0               2                  2                      2               1              4                         2                            1                1                0          2                        2            0.260994      0.690017       -0.415957       0.293945          5          14          0               1              1.368831               -0.467057               1.735317          -1.626123             2.853582                 0.0
0                     1    0             2           1                  1               0.613672               0            1                        4                   2               17                     0       0.957325      0.970481              2               2                  0                      3               4              1                         1                            0                2                1          2                        2            0.682604     -0.228278        1.132177       0.723886         10           1          1               1              0.128570                0.971032               1.735317           1.160031            -0.947412                 0.0
..                  ...  ...           ...         ...                ...                    ...             ...          ...                      ...                 ...              ...                   ...            ...           ...            ...             ...                ...                    ...             ...            ...                       ...                          ...              ...              ...        ...                      ...                 ...           ...             ...            ...        ...         ...        ...             ...                   ...                     ...                    ...                ...                  ...                 ...
106                   1    1             2           2                  1              -0.524848               0            0                        0                   9                1                     0      -0.919382     -1.049454              0               1                  0                      3               5              3                         1                            2                1                0          2                        2            0.993403     -0.199645        2.558849       0.783481         10           3          0               1             -0.998940                0.971032              -1.571616          -0.233046            -0.947412                 0.0
270                   1    1             2           1                  2               1.352210               0            1                        1                   5                4                     0       1.031267      0.970481              0               1                  1                      3               5              0                         1                            2                1                2          0                        2            1.202121      1.929408        0.207826       1.129881         12          18          1               0             -0.096932               -0.754675               1.597528           1.392211            -0.947412                 0.0
860                   1    0             1           0                  1              -0.938378               0            0                        4                   0                9                     3      -0.919382     -0.651914              0               1                  1                      2               1              3                         0                            2                0                1          2                        2            0.198379      0.628661        0.654562      -0.054583          0          23          0               0              0.015819                1.258650               0.357428          -1.045674             0.953085                 0.0
435                   0    2             2           1                  0              -0.726882               0            1                        4                   6               15                     5       1.024225      0.970481              2               2                  2                      3               3              3                         1                            0                0                1          0                        0            0.750532     -0.058526       -0.037158       1.077203          4          27          0               0              1.481582                0.395797              -0.331516          -0.000866             0.953085                 0.0
102                   1    0             0           1                  0               0.979403               0            0                        3                   9                3                     0       0.393961     -0.164837              0               0                  1                      1               0              4                         0                            2                1                2          3                        0           -0.941979     -1.559703       -0.807107      -0.706410          5          16          2               0             -1.111691               -0.179439              -0.055938           1.624390            -0.947412                 0.0

[670 rows x 40 columns]

In [154]:
data_train.isnull().sum()

months_as_customer             0
age                            0
policy_state                   0
policy_csl                     0
policy_deductable              0
policy_annual_premium          0
umbrella_limit                 0
insured_sex                    0
insured_education_level        0
insured_occupation             0
insured_hobbies                0
insured_relationship           0
capital-gains                  0
capital-loss                   0
incident_type                  0
collision_type                 0
incident_severity              0
authorities_contacted          0
incident_state                 0
incident_city                  0
incident_hour_of_the_day       0
number_of_vehicles_involved    0
property_damage                0
bodily_injuries                0
witnesses                      0
police_report_available        0
total_claim_amount             0
injury_claim                   0
property_claim                 0
vehicle_claim                  0
auto_make                      0
auto_model                     0
auto_year                      0
fraud_reported                 0
day_policy_bind_date           0
month_policy_bind_date         0
year_policy_bind_date          0
day_incident_date              0
month_incident_date            0
year_incident_date             0
dtype: int64

In [155]:
x_train=data_train.drop('fraud_reported',axis=1)
y_train=data_train['fraud_reported']

# x_test=data_test.drop('fraud_reported',axis=1)
# y_test=data_test['fraud_reported']

In [156]:
y_train.value_counts()

fraud_reported
0    511
1    159
Name: count, dtype: int64

In [157]:
class_0_count = np.sum(y_train == 0)
class_1_count = np.sum(y_train == 1)
gen_x_times = class_0_count / class_1_count
print(f"Lớp 0 (đa số): {class_0_count} mẫu")
print(f"Lớp 1 (thiểu số): {class_1_count} mẫu")

Lớp 0 (đa số): 511 mẫu
Lớp 1 (thiểu số): 159 mẫu

In [158]:
x_train_minority = x_train[y_train == 1]
y_train_minority = y_train[y_train == 1]

In [159]:
print(gen_x_times)

3.2138364779874213

In [160]:
print(y_train)

703    1
311    1
722    1
629    1
0      1
      ..
106    1
270    0
860    0
435    0
102    0
Name: fraud_reported, Length: 670, dtype: int32

In [161]:
# gen_y_train = gen_y_train.to_frame()
# # x_train_minority= x_train_minority.to_frame()
# y_train_minority = y_train_minority.to_frame()

In [162]:
# print(type(x_train_balanced))  # Phải là <class 'pandas.core.frame.DataFrame'>
# print(type(y_train_balanced))  # Phải là <class 'pandas.core.frame.DataFrame'>

In [163]:
object_cols_test=dict(np.load(f'{exps_dir}/exp1/columns_dtype.npz',allow_pickle=True))['category_columns']
numeric_cols_test=dict(np.load(f'{exps_dir}/exp1/columns_dtype.npz',allow_pickle=True))['numeric_columns']
# for column in outliers_list:
#     data_test = remove_outliers_iqr(data_test, column)
# data_test['collision_type'].replace('?',np.nan,inplace=True)
# data_test['collision_type'].fillna(method='ffill',inplace=True)
# data_test[['property_damage','police_report_available']].replace('?','Unknow',inplace=True)
# (data_test=='?').sum()
label_encoders = {}
for column in object_cols_test:
    label_encoder = LabelEncoder()
    data_test[column] = label_encoder.fit_transform(data_test[column])
    label_encoders[column] = label_encoder  # Lưu trữ label encoder nếu cần sau này

scaler = StandardScaler()
data_test[numeric_cols_test] = scaler.fit_transform(data_test[numeric_cols_test])

x_test=data_test.drop('fraud_reported',axis=1)
y_test=data_test['fraud_reported']
data_test.to_excel(f'{save_dir}/df_test_minmax.xlsx', index=False)
x_test.to_excel(f'{save_dir}/x_test.xlsx', index=False)
y_test.to_excel(f'{save_dir}/y_test.xlsx', index=False)

In [164]:
x_test_minority = x_test[y_test == 1]

In [165]:
y_train_minority.value_counts()

fraud_reported
1    159
Name: count, dtype: int64

In [166]:
gen_y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [182]:
x_test.shape

(330, 39)

In [ ]:
y_train.value_counts()

In [184]:
# from imblearn.over_sampling import SMOTE
# x_train, y_train = SMOTE().fit_resample(x_train, y_train)
from tabgan.sampler import GANGenerator

gen_x, gen_y = GANGenerator(gen_x_times=1000000000000000000000000000000000000000000000000000000000000, 
                                cat_cols=None,
                                # bot_filter_quantile=0.001, 
                                # top_filter_quantile=0.999,
                                is_post_process=True,
                                adversarial_model_params={
                                    "metrics": "accuracy", 
                                    "max_depth": 2, 
                                    "max_bin": 100, 
                                    "learning_rate": 0.02, 
                                    "random_state": 42, 
                                    "n_estimators": 100,
                                },
                                pregeneration_frac=2,
                                only_generated_data=True,
                                
                                gen_params = {
                                    "batch_size": 100, 
                                    "patience": 3, 
                                    "epochs" : 9,
                                    "force_col_wise":True,
                                }).generate_data_pipe(x_train, pd.DataFrame(y_train), x_test, 
                                                      deep_copy=True, only_adversarial=False, 
                                                      use_adversarial=True)

print(gen_x.shape, gen_y.shape)

Fitting CTGAN transformers for each column:   0%|          | 0/40 [00:00<?, ?it/s]

Training CTGAN, epochs::   0%|          | 0/9 [00:00<?, ?it/s]

KeyboardInterrupt:

In [168]:
x_test.isnull().sum()

months_as_customer             0
age                            0
policy_state                   0
policy_csl                     0
policy_deductable              0
policy_annual_premium          0
umbrella_limit                 0
insured_sex                    0
insured_education_level        0
insured_occupation             0
insured_hobbies                0
insured_relationship           0
capital-gains                  0
capital-loss                   0
incident_type                  0
collision_type                 0
incident_severity              0
authorities_contacted          0
incident_state                 0
incident_city                  0
incident_hour_of_the_day       0
number_of_vehicles_involved    0
property_damage                0
bodily_injuries                0
witnesses                      0
police_report_available        0
total_claim_amount             0
injury_claim                   0
property_claim                 0
vehicle_claim                  0
auto_make                      0
auto_model                     0
auto_year                      0
day_policy_bind_date           0
month_policy_bind_date         0
year_policy_bind_date          0
day_incident_date              0
month_incident_date            0
year_incident_date             0
dtype: int64

In [169]:
data_train.shape

(670, 40)

In [170]:
print(gen_x.shape, gen_y.shape)

(25, 39) (25,)

In [171]:
gen_y.value_counts()

fraud_reported
0    14
1    11
Name: count, dtype: int64

In [172]:
gen_x.to_excel(f'{save_dir}/gen_x.xlsx', index=False)
gen_y.to_excel(f'{save_dir}/gen_y.xlsx', index=False)

In [173]:
y_train

703    1
311    1
722    1
629    1
0      1
      ..
106    1
270    0
860    0
435    0
102    0
Name: fraud_reported, Length: 670, dtype: int32

In [174]:
x_train

     months_as_customer  age  policy_state  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  insured_sex  insured_education_level  insured_occupation  insured_hobbies  insured_relationship  capital-gains  capital-loss  incident_type  collision_type  incident_severity  authorities_contacted  incident_state  incident_city  incident_hour_of_the_day  number_of_vehicles_involved  property_damage  bodily_injuries  witnesses  police_report_available  total_claim_amount  injury_claim  property_claim  vehicle_claim  auto_make  auto_model  auto_year  day_policy_bind_date  month_policy_bind_date  year_policy_bind_date  day_incident_date  month_incident_date  year_incident_date
703                   1    0             0           1                  1              -1.770734               0            1                        2                  11                6                     4       1.270697      0.970481              0               1                  2                      0               4              1                         0                            2                1                1          1                        0            0.249230     -0.612776        0.358110       0.416329          8          24          2              0.579574               -0.179439              -1.020460          -1.393943            -0.947412                 0.0
311                   0    2             1           0                  2              -1.979562               0            1                        4                  11                0                     1      -0.919382      0.175400              0               0                  0                      0               4              4                         1                            2                1                0          3                        1           -0.845210     -0.976821       -0.374783      -0.834115          6           6          0             -0.547936               -0.179439               0.908584           0.115223             0.953085                 0.0
722                   1    0             2           0                  2               0.675544               0            0                        0                   5               14                     4      -0.919382     -0.691310              2               2                  0                      0               6              5                         2                            0                2                2          1                        0            1.224890      1.953951        1.988592       0.695152         11          15          1              1.481582                0.108179              -0.744883           0.115223            -0.947412                 0.0
629                   1    0             0           0                  2              -0.492901               0            0                        2                   2                5                     5      -0.919382     -1.049454              0               2                  2                      2               1              4                         2                            1                1                0          2                        2            0.260994      0.690017       -0.415957       0.293945          5          14          0              1.368831               -0.467057               1.735317          -1.626123             2.853582                 0.0
0                     1    0             2           1                  1               0.613672               0            1                        4                   2               17                     0       0.957325      0.970481              2               2                  0                      3               4              1                         1                            0                2                1          2                        2            0.682604     -0.228278        1.132177       0.723886         10           1          1              0.128570                0.971032               1.735317           1.160031            -0.947412                 0.0
..                  ...  ...           ...         ...                ...                    ...             ...          ...                      ...                 ...              ...                   ...            ...           ...            ...             ...                ...                    ...             ...            ...                       ...                          ...              ...              ...        ...                      ...                 ...           ...             ...            ...        ...         ...        ...                   ...                     ...                    ...                ...                  ...                 ...
106                   1    1             2           2                  1              -0.524848               0            0                        0                   9                1                     0      -0.919382     -1.049454              0               1                  0                      3               5              3                         1                            2                1                0          2                        2            0.993403     -0.199645        2.558849       0.783481         10           3          0             -0.998940                0.971032              -1.571616          -0.233046            -0.947412                 0.0
270                   1    1             2           1                  2               1.352210               0            1                        1                   5                4                     0       1.031267      0.970481              0               1                  1                      3               5              0                         1                            2                1                2          0                        2            1.202121      1.929408        0.207826       1.129881         12          18          1             -0.096932               -0.754675               1.597528           1.392211            -0.947412                 0.0
860                   1    0             1           0                  1              -0.938378               0            0                        4                   0                9                     3      -0.919382     -0.651914              0               1                  1                      2               1              3                         0                            2                0                1          2                        2            0.198379      0.628661        0.654562      -0.054583          0          23          0              0.015819                1.258650               0.357428          -1.045674             0.953085                 0.0
435                   0    2             2           1                  0              -0.726882               0            1                        4                   6               15                     5       1.024225      0.970481              2               2                  2                      3               3              3                         1                            0                0                1          0                        0            0.750532     -0.058526       -0.037158       1.077203          4          27          0              1.481582                0.395797              -0.331516          -0.000866             0.953085                 0.0
102                   1    0             0           1                  0               0.979403               0            0                        3                   9                3                     0       0.393961     -0.164837              0               0                  1                      1               0              4                         0                            2                1                2          3                        0           -0.941979     -1.559703       -0.807107      -0.706410          5          16          2             -1.111691               -0.179439              -0.055938           1.624390            -0.947412                 0.0

[670 rows x 39 columns]

In [175]:
gen_x

    months_as_customer  age  policy_state  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  insured_sex  insured_education_level  insured_occupation  insured_hobbies  insured_relationship  capital-gains  capital-loss  incident_type  collision_type  incident_severity  authorities_contacted  incident_state  incident_city  incident_hour_of_the_day  number_of_vehicles_involved  property_damage  bodily_injuries  witnesses  police_report_available  total_claim_amount  injury_claim  property_claim  vehicle_claim  auto_make  auto_model  auto_year  day_policy_bind_date  month_policy_bind_date  year_policy_bind_date  day_incident_date  month_incident_date  year_incident_date
0                    1    2             2           0                  1               0.319438               5            1                        2                   2               15                     1       0.957325     -0.791590              2               0                  0                      2               6              6                         0                            0                2                2          0                        2           -0.019826      0.612299       -0.455072      -0.069482          8           7          0             -0.886189                0.395797               1.184162           1.043941            -0.947412                 0.0
1                    0    2             1           1                  1               0.079028               4            1                        1                   9               10                     2       0.753106     -1.131827              0               1                  0                      0               0              6                         0                            2                2                2          3                        2            0.067456     -0.426662        0.732792       0.016187          3          32          1              0.917827                1.546268               0.633006          -0.465225            -0.947412                 0.0
2                    0    2             2           0                  1              -0.817344               6            0                        5                   7               15                     3       0.911552     -0.623262              0               1                  1                      0               0              4                         2                            2                0                1          3                        1            0.023435      0.289158        0.312819      -0.123224         10           2          2              0.805076               -0.179439               1.459740           1.043941             0.953085                 0.0
3                    1    0             1           1                  1               0.847491               2            1                        6                   3                9                     2       1.013662     -0.343910              0               2                  2                      1               1              0                         0                            2                1                0          0                        0           -0.081303     -0.389849       -0.370665       0.083232         12          18          2              0.692325               -0.179439               1.046373           1.160031            -0.947412                 0.0
4                    0    2             2           0                  0               0.596971               4            0                        6                   7                0                     0       1.555900     -0.830986              2               1                  1                      0               1              4                         1                            0                2                0          1                        1            0.092881     -0.285544        1.016891      -0.058308         12           9          2             -0.998940               -1.042293               0.908584          -1.510033             0.953085                 0.0
5                    1    2             0           0                  1               0.828201               5            0                        2                   0               15                     5       0.534802     -0.533726              0               2                  2                      0               1              3                         0                            2                0                0          1                        0           -0.452821     -0.009441        0.012251      -0.635641         10           3          0              0.917827               -1.329911               1.459740          -0.929584            -0.947412                 0.0
6                    1    0             0           1                  2               1.922199               6            1                        1                  13               10                     1       0.710853     -0.522982              0               0                  1                      1               6              4                         0                            2                0                2          0                        0            0.096297     -0.602550        0.378697       0.193910         10           3          0              1.368831               -0.754675               1.597528           1.043941            -0.947412                 0.0
7                    1    1             1           0                  0               0.176931               5            1                        6                   2                7                     4       0.932678     -0.419120              2               0                  0                      1               0              6                         3                            0                2                0          0                        1            0.621506      1.303577       -0.107153       0.559998          5          14          2              0.241321               -1.042293               0.219640          -1.045674            -0.947412                 0.0
8                    1    2             1           2                  0               0.010807               6            1                        2                   4               15                     3       0.513676     -0.519400              0               1                  0                      2               2              0                         1                            3                0                2          2                        0           -0.224749     -0.584143        0.415754      -0.270617          0          33          2             -1.562696                0.395797              -1.571616          -0.116956             0.953085                 0.0
9                    1    0             1           0                  1              -0.585507               9            1                        4                   6               10                     2       0.291851     -1.063780              0               2                  2                      2               1              5                         0                            2                0                0          1                        1           -0.224749     -0.584143        0.415754      -0.270617          0          23          0             -0.773438               -1.042293              -0.331516           1.043941            -0.947412                 0.0
10                   1    0             0           1                  1               0.176688               5            0                        2                  11                4                     2       1.591110     -1.547275              0               0                  0                      0               1              1                         0                            2                1                1          3                        2            0.031405     -0.322357        0.942778      -0.115775         10           1          1             -0.998940                1.546268              -0.469305          -1.277853            -0.947412                 0.0
11                   1    1             1           1                  0               0.061194               3            1                        1                   1                8                     0      -0.074336     -0.838149              1               1                  1                      4               5              0                         1                            0                0                0          0                        0           -1.792029     -1.428810       -1.416479      -1.774876          6          10          1              1.481582                0.108179               1.046373           0.463493             0.953085                 0.0
12                   0    2             2           2                  2               0.007451               3            0                        2                   6                1                     4       1.330554     -0.594611              2               0                  2                      2               6              4                         2                            0                0                1          3                        0            0.290214     -0.420527        0.745144       0.323743         11          21          0             -0.998940                0.683414               0.633006          -0.465225            -0.947412                 0.0
13                   1    2             2           2                  1              -0.458771               1            0                        3                   8               17                     3       0.372835     -1.658300              2               0                  0                      0               6              4                         2                            0                2                1          2                        1            0.020399     -0.175103       -0.154503       0.114094         11          21          2              1.368831                0.971032               0.770795          -1.277853            -0.947412                 0.0
14                   1    2             1           0                  0              -1.646223               2            1                        3                   3                5                     1       0.172136     -0.111116              3               2                  1                      4               5              4                         1                            0                2                2          1                        1           -1.817834     -1.347002       -1.441184      -1.825958         11          15          1              0.241321                0.108179               0.081851          -0.929584            -0.947412                 0.0
15                   1    0             2           0                  1              -0.976795               5            0                        0                   2               12                     3       0.689727     -0.512237              1               0                  1                      4               1              6                         1                            0                1                1          1                        2           -1.822768     -1.383816       -1.371188      -1.841389         11          19          1              0.015819                0.683414               1.597528          -1.393943            -0.947412                 0.0
16                   1    1             2           1                  2               0.614077               4            1                        6                  12               17                     2       0.749585     -0.017998              2               1                  0                      3               6              5                         0                            0                1                0          2                        1            0.238225      0.890447       -0.315081       0.183800          2          37          0              1.594333               -0.754675               0.081851          -0.581315            -0.947412                 0.0
17                   0    2             0           0                  2              -0.956090               4            1                        0                   5               19                     3      -0.215177     -1.991374              0               2                  2                      3               1              5                         2                            2                2                1          2                        1            1.522028      1.389475        2.904709       1.021864          6           8          0              1.030578                1.258650              -1.020460           1.392211            -0.947412                 0.0
18                   1    1             2           2                  0              -0.771041               4            1                        0                   8                5                     2       1.668573     -0.580285              2               0                  2                      0               6              0                         2                            0                0                2          1                        1            0.351312     -0.488018        0.609270       0.462090          8          12          1              0.579574                1.258650               0.633006          -0.233046             0.953085                 0.0
19                   1    0             0           1                  0               1.318767               4            0                        6                   5               16                     3       0.566491     -0.748613              2               0                  1                      3               1              5                         1                            0                2                2          2                        0            0.373702     -0.379623        0.827492       0.408880          2          38          0              0.692325                1.546268              -0.882671          -0.929584            -0.947412                 0.0
20                   1    0             2           1                  0               2.469501               4            1                        1                  13               11                     4       0.235515     -0.841730              2               1                  2                      3               6              2                         0                            0                1                2          1                        2           -0.239929     -0.680267        0.222237      -0.216875         13          20          1              1.594333               -1.042293              -0.882671          -0.465225             0.953085                 0.0
21                   1    0             0           0                  1              -1.417216               6            0                        4                   2                3                     4       1.496042      0.171818              2               0                  0                      1               4              5                         3                            0                1                1          3                        0            0.780891      1.475374        1.506859       0.321615          0          33          1              1.481582                1.258650              -0.331516           0.231313             0.953085                 0.0
22                   1    0             1           2                  2               0.002113               5            0                        0                  11               15                     2      -0.088420      0.411775              1               0                  1                      4               0              0                         1                            0                0                0          0                        1           -1.754081     -1.408358       -1.243549      -1.771683          4          27          2              1.707084                0.971032              -1.158249           0.347403             0.953085                 0.0
23                   1    0             2           1                  2              -1.251295               4            1                        4                  10                5                     5       0.439734     -0.562378              2               0                  1                      1               1              0                         2                            0                0                0          0                        0            1.156583      1.880323        0.183122       1.085184          5          13          2             -0.886189               -0.754675              -1.433827          -1.277853             0.953085                 0.0
24                   1    0             1           2                  2              -1.316119               5            0                        6                   5                0                     0       0.714374     -1.690533              2               0                  2                      2               5              0                         0                            0                1                2          2                        2            0.364973      0.595938       -0.463306       0.476457          8          12          1              0.241321               -1.329911              -0.331516          -0.116956            -0.947412                 0.0

In [176]:
gen_y

0     1
1     1
2     1
3     0
4     0
5     0
6     0
7     1
8     1
9     1
10    0
11    0
12    0
13    0
14    1
15    0
16    1
17    0
18    1
19    0
20    0
21    1
22    0
23    1
24    0
Name: fraud_reported, dtype: int32

In [177]:
print(data_train.shape)

(670, 40)

In [178]:
x_train.to_excel(f'{save_dir}/x_train.xlsx', index=False)
y_train.to_excel(f'{save_dir}/y_train.xlsx', index=False)

In [179]:
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)
class_weights_dict = {i : class_weights[i] for i in range(len(class_weights))}
np.savez(f'{save_dir}/class_weights_dict.npz', class_weights_dict = class_weights_dict)
class_weights_dict

{0: 0.6555772994129159, 1: 2.106918238993711}

In [180]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)
print(f"+ X_train: {len(x_train)}")
for fold, (train_idx, valid_idx) in enumerate(kfold.split(x_train, y_train)):
    print(f'Fold {fold}: ')
    print(f'+ train_idx: {train_idx}')
    print(f'+ valid_idx: {valid_idx}')
    print(f'+ train / valid: {valid_idx}')
    pass

+ X_train: 670
Fold 0:
+ train_idx: [  0   1   3   4   5   7   8   9  11  12  13  14  15  16  17  19  20  21
  22  23  25  26  27  28  29  32  33  34  35  36  37  38  40  42  43  45
  46  47  48  50  52  53  57  58  59  61  62  64  66  67  68  71  73  74
  75  79  80  83  84  85  87  88  89  91  92  93  94  95  96  97  98  99
 100 102 103 104 105 106 107 111 112 113 114 115 116 117 119 121 122 123
 124 125 126 127 128 129 130 134 137 138 139 140 141 142 143 144 145 146
 147 149 150 151 152 153 154 156 157 159 160 161 162 163 166 167 168 169
 170 171 172 173 174 175 177 178 179 180 183 184 185 186 187 188 189 190
 191 193 194 195 196 197 198 200 201 202 203 205 206 207 209 213 214 215
 216 217 218 219 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 251 252 253 254
 255 258 259 260 261 262 263 265 266 267 268 269 270 271 272 273 274 276
 277 279 280 282 283 285 286 287 288 290 291 293 294 295 296 297 298 301
 303 304 305 307 308 309 312 313 314 315 316 317 320 321 322 323 324 325
 326 327 328 329 330 332 333 335 337 339 340 341 342 343 344 345 347 348
 349 350 351 353 355 356 357 358 359 363 364 365 366 368 369 370 371 372
 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390
 391 392 394 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410
 411 412 413 414 415 416 417 418 419 421 422 423 424 425 426 427 428 429
 430 431 432 433 434 435 438 439 440 441 442 444 445 446 447 448 449 450
 451 453 454 455 457 458 459 460 461 462 465 466 467 468 469 470 471 472
 474 475 476 479 483 484 485 486 487 488 489 490 491 492 493 494 495 496
 497 498 500 501 502 503 504 505 506 508 509 510 512 513 514 515 517 518
 519 520 521 522 524 525 526 527 528 529 530 531 532 533 535 536 538 540
 541 542 543 544 545 546 547 548 549 550 552 554 555 557 558 559 560 561
 562 563 564 565 566 567 568 569 571 572 573 574 575 576 577 579 580 581
 582 583 584 585 586 587 588 589 590 591 592 593 595 596 597 598 599 600
 601 603 604 605 606 607 608 610 611 612 613 614 615 618 619 620 621 626
 629 630 631 632 634 635 636 637 638 641 642 643 644 645 646 647 648 649
 651 652 653 654 655 658 659 660 662 663 664 667 668 669]
+ valid_idx: [  2   6  10  18  24  30  31  39  41  44  49  51  54  55  56  60  63  65
  69  70  72  76  77  78  81  82  86  90 101 108 109 110 118 120 131 132
 133 135 136 148 155 158 164 165 176 181 182 192 199 204 208 210 211 212
 220 221 250 256 257 264 275 278 281 284 289 292 299 300 302 306 310 311
 318 319 331 334 336 338 346 352 354 360 361 362 367 393 395 420 436 437
 443 452 456 463 464 473 477 478 480 481 482 499 507 511 516 523 534 537
 539 551 553 556 570 578 594 602 609 616 617 622 623 624 625 627 628 633
 639 640 650 656 657 661 665 666]
+ train / valid: [  2   6  10  18  24  30  31  39  41  44  49  51  54  55  56  60  63  65
  69  70  72  76  77  78  81  82  86  90 101 108 109 110 118 120 131 132
 133 135 136 148 155 158 164 165 176 181 182 192 199 204 208 210 211 212
 220 221 250 256 257 264 275 278 281 284 289 292 299 300 302 306 310 311
 318 319 331 334 336 338 346 352 354 360 361 362 367 393 395 420 436 437
 443 452 456 463 464 473 477 478 480 481 482 499 507 511 516 523 534 537
 539 551 553 556 570 578 594 602 609 616 617 622 623 624 625 627 628 633
 639 640 650 656 657 661 665 666]
Fold 1:
+ train_idx: [  1   2   3   4   5   6   8  10  12  13  14  16  17  18  19  20  21  24
  25  26  27  30  31  32  34  35  36  37  38  39  40  41  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  62  63  64  65  67
  69  70  71  72  74  76  77  78  80  81  82  85  86  87  90  91  94  95
  96  97  98  99 100 101 102 103 105 106 107 108 109 110 111 112 113 115
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 138 139 141 142 143 144 146 147 148 149 150 151 152 154 155 156 157
 158 159 160 161 162 164 165 166 168 169 170 171 172 173 175 176 179 180
 181 182 183 185 186 187 189 190 191 192 193 194 195 197 198 199 200 201
 202 204 205 206 207 208 210 211 212 214 216 217 219 220 221 222 223 224
 225 226 229 230 232 233 237 239 240 241 242 243 245 246 250 251 252 253
 254 255 256 257 258 261 262 263 264 266 267 268 269 270 272 273 275 276
 278 279 280 281 282 283 284 285 287 288 289 292 293 295 297 298 299 300
 301 302 303 304 305 306 307 308 309 310 311 312 313 315 316 317 318 319
 322 323 324 325 326 327 328 330 331 333 334 336 337 338 339 342 343 344
 345 346 347 348 350 351 352 354 358 359 360 361 362 364 365 366 367 368
 369 370 371 372 373 374 376 378 379 380 383 384 385 386 387 388 389 391
 392 393 394 395 396 397 398 399 400 401 402 403 404 406 407 408 409 410
 411 413 414 415 416 417 418 419 420 422 423 424 425 426 427 428 429 430
 432 433 435 436 437 438 439 440 441 442 443 444 445 446 448 450 452 453
 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 471 472
 473 474 475 476 477 478 480 481 482 483 484 485 486 487 488 489 490 491
 492 494 495 496 498 499 500 501 502 503 504 505 507 508 509 510 511 512
 513 516 517 518 520 522 523 524 525 526 527 528 530 531 532 534 535 536
 537 538 539 540 542 543 544 546 547 549 551 552 553 555 556 557 558 559
 560 561 562 563 564 565 566 567 568 569 570 571 573 574 575 578 579 580
 581 582 583 585 587 590 592 593 594 595 596 597 598 600 602 604 605 608
 609 611 613 614 616 617 618 619 620 621 622 623 624 625 626 627 628 630
 631 632 633 634 635 636 638 639 640 642 643 645 646 647 648 649 650 651
 652 654 656 657 659 660 661 663 664 665 666 667 668 669]
+ valid_idx: [  0   7   9  11  15  22  23  28  29  33  42  43  61  66  68  73  75  79
  83  84  88  89  92  93 104 114 116 117 137 140 145 153 163 167 174 177
 178 184 188 196 203 209 213 215 218 227 228 231 234 235 236 238 244 247
 248 249 259 260 265 271 274 277 286 290 291 294 296 314 320 321 329 332
 335 340 341 349 353 355 356 357 363 375 377 381 382 390 405 412 421 431
 434 447 449 451 470 479 493 497 506 514 515 519 521 529 533 541 545 548
 550 554 572 576 577 584 586 588 589 591 599 601 603 606 607 610 612 615
 629 637 641 644 653 655 658 662]
+ train / valid: [  0   7   9  11  15  22  23  28  29  33  42  43  61  66  68  73  75  79
  83  84  88  89  92  93 104 114 116 117 137 140 145 153 163 167 174 177
 178 184 188 196 203 209 213 215 218 227 228 231 234 235 236 238 244 247
 248 249 259 260 265 271 274 277 286 290 291 294 296 314 320 321 329 332
 335 340 341 349 353 355 356 357 363 375 377 381 382 390 405 412 421 431
 434 447 449 451 470 479 493 497 506 514 515 519 521 529 533 541 545 548
 550 554 572 576 577 584 586 588 589 591 599 601 603 606 607 610 612 615
 629 637 641 644 653 655 658 662]
Fold 2:
+ train_idx: [  0   1   2   4   6   7   8   9  10  11  13  14  15  18  20  21  22  23
  24  27  28  29  30  31  32  33  34  35  36  38  39  40  41  42  43  44
  47  49  51  52  53  54  55  56  58  59  60  61  62  63  64  65  66  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  95  96  97  98  99 100 101 102 103 104 105
 106 108 109 110 111 112 114 115 116 117 118 119 120 121 122 123 125 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 143 145 146 147 148
 150 151 153 155 156 158 159 160 161 163 164 165 166 167 170 171 174 176
 177 178 181 182 183 184 186 187 188 189 191 192 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 221 223 224 227 228 230 231 232 233 234 235 236 238 239 240 241 242
 243 244 246 247 248 249 250 251 252 253 254 256 257 258 259 260 262 264
 265 266 267 269 270 271 273 274 275 276 277 278 279 281 282 284 286 288
 289 290 291 292 293 294 295 296 297 299 300 302 303 306 307 308 310 311
 313 314 315 317 318 319 320 321 323 324 325 329 330 331 332 334 335 336
 337 338 339 340 341 342 343 345 346 347 348 349 351 352 353 354 355 356
 357 358 359 360 361 362 363 366 367 368 371 372 373 375 376 377 378 379
 381 382 384 385 386 387 389 390 391 392 393 394 395 397 400 401 402 403
 405 406 407 410 412 413 414 415 416 418 419 420 421 423 424 425 427 431
 433 434 435 436 437 438 439 440 441 442 443 447 449 450 451 452 453 454
 455 456 458 459 460 461 463 464 466 468 469 470 471 472 473 474 475 476
 477 478 479 480 481 482 484 487 488 489 491 492 493 494 495 496 497 498
 499 500 502 503 504 505 506 507 508 509 510 511 514 515 516 517 518 519
 520 521 522 523 524 525 527 529 530 531 533 534 536 537 538 539 540 541
 542 545 546 547 548 549 550 551 552 553 554 555 556 557 558 560 561 562
 563 564 565 566 567 569 570 571 572 576 577 578 580 581 584 585 586 587
 588 589 591 592 593 594 595 596 597 599 600 601 602 603 606 607 608 609
 610 611 612 614 615 616 617 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 635 636 637 638 639 640 641 644 645 646 649 650 652 653
 654 655 656 657 658 659 661 662 663 664 665 666 667 668]
+ valid_idx: [  3   5  12  16  17  19  25  26  37  45  46  48  50  57  67  94 107 113
 124 126 141 142 144 149 152 154 157 162 168 169 172 173 175 179 180 185
 190 193 194 195 222 225 226 229 237 245 255 261 263 268 272 280 283 285
 287 298 301 304 305 309 312 316 322 326 327 328 333 344 350 364 365 369
 370 374 380 383 388 396 398 399 404 408 409 411 417 422 426 428 429 430
 432 444 445 446 448 457 462 465 467 483 485 486 490 501 512 513 526 528
 532 535 543 544 559 568 573 574 575 579 582 583 590 598 604 605 613 618
 634 642 643 647 648 651 660 669]
+ train / valid: [  3   5  12  16  17  19  25  26  37  45  46  48  50  57  67  94 107 113
 124 126 141 142 144 149 152 154 157 162 168 169 172 173 175 179 180 185
 190 193 194 195 222 225 226 229 237 245 255 261 263 268 272 280 283 285
 287 298 301 304 305 309 312 316 322 326 327 328 333 344 350 364 365 369
 370 374 380 383 388 396 398 399 404 408 409 411 417 422 426 428 429 430
 432 444 445 446 448 457 462 465 467 483 485 486 490 501 512 513 526 528
 532 535 543 544 559 568 573 574 575 579 582 583 590 598 604 605 613 618
 634 642 643 647 648 651 660 669]
Fold 3:
+ train_idx: [  0   1   2   3   4   5   6   7   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  37
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  54  55  56  57
  58  60  61  62  63  64  65  66  67  68  69  70  71  72  73  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  98  99 101 102 104 105 106 107 108 109 110 113 114 116 117 118 120 121
 124 126 128 130 131 132 133 134 135 136 137 138 140 141 142 144 145 148
 149 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
 169 170 172 173 174 175 176 177 178 179 180 181 182 184 185 187 188 189
 190 191 192 193 194 195 196 199 200 201 203 204 205 206 208 209 210 211
 212 213 214 215 216 217 218 220 221 222 225 226 227 228 229 230 231 234
 235 236 237 238 240 241 242 243 244 245 247 248 249 250 251 252 255 256
 257 259 260 261 263 264 265 268 269 270 271 272 273 274 275 276 277 278
 280 281 283 284 285 286 287 288 289 290 291 292 294 295 296 298 299 300
 301 302 304 305 306 308 309 310 311 312 313 314 315 316 318 319 320 321
 322 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 343
 344 345 346 349 350 352 353 354 355 356 357 360 361 362 363 364 365 366
 367 369 370 372 374 375 377 378 379 380 381 382 383 385 387 388 389 390
 391 392 393 395 396 397 398 399 401 404 405 406 408 409 411 412 413 417
 418 420 421 422 426 427 428 429 430 431 432 434 435 436 437 443 444 445
 446 447 448 449 451 452 454 455 456 457 458 459 460 461 462 463 464 465
 466 467 470 471 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 489 490 491 492 493 497 498 499 501 502 504 505 506 507 508 510 511 512
 513 514 515 516 519 520 521 523 524 526 528 529 532 533 534 535 537 539
 540 541 543 544 545 546 548 550 551 553 554 555 556 559 560 561 562 563
 564 565 566 568 569 570 571 572 573 574 575 576 577 578 579 582 583 584
 585 586 587 588 589 590 591 594 596 598 599 600 601 602 603 604 605 606
 607 609 610 612 613 614 615 616 617 618 619 620 622 623 624 625 626 627
 628 629 630 633 634 637 639 640 641 642 643 644 647 648 650 651 652 653
 654 655 656 657 658 659 660 661 662 664 665 666 667 669]
+ valid_idx: [  8  36  38  53  59  74  96  97 100 103 111 112 115 119 122 123 125 127
 129 139 143 146 147 150 151 171 183 186 197 198 202 207 219 223 224 232
 233 239 246 253 254 258 262 266 267 279 282 293 297 303 307 317 323 324
 325 342 347 348 351 358 359 368 371 373 376 384 386 394 400 402 403 407
 410 414 415 416 419 423 424 425 433 438 439 440 441 442 450 453 468 469
 472 487 488 494 495 496 500 503 509 517 518 522 525 527 530 531 536 538
 542 547 549 552 557 558 567 580 581 592 593 595 597 608 611 621 631 632
 635 636 638 645 646 649 663 668]
+ train / valid: [  8  36  38  53  59  74  96  97 100 103 111 112 115 119 122 123 125 127
 129 139 143 146 147 150 151 171 183 186 197 198 202 207 219 223 224 232
 233 239 246 253 254 258 262 266 267 279 282 293 297 303 307 317 323 324
 325 342 347 348 351 358 359 368 371 373 376 384 386 394 400 402 403 407
 410 414 415 416 419 423 424 425 433 438 439 440 441 442 450 453 468 469
 472 487 488 494 495 496 500 503 509 517 518 522 525 527 530 531 536 538
 542 547 549 552 557 558 567 580 581 592 593 595 597 608 611 621 631 632
 635 636 638 645 646 649 663 668]
Fold 4:
+ train_idx: [  0   2   3   5   6   7   8   9  10  11  12  15  16  17  18  19  22  23
  24  25  26  28  29  30  31  33  36  37  38  39  41  42  43  44  45  46
  48  49  50  51  53  54  55  56  57  59  60  61  63  65  66  67  68  69
  70  72  73  74  75  76  77  78  79  81  82  83  84  86  88  89  90  92
  93  94  96  97 100 101 103 104 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 122 123 124 125 126 127 129 131 132 133 135 136 137 139
 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 157 158
 162 163 164 165 167 168 169 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 188 190 192 193 194 195 196 197 198 199 202 203 204
 207 208 209 210 211 212 213 215 218 219 220 221 222 223 224 225 226 227
 228 229 231 232 233 234 235 236 237 238 239 244 245 246 247 248 249 250
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 271 272
 274 275 277 278 279 280 281 282 283 284 285 286 287 289 290 291 292 293
 294 296 297 298 299 300 301 302 303 304 305 306 307 309 310 311 312 314
 316 317 318 319 320 321 322 323 324 325 326 327 328 329 331 332 333 334
 335 336 338 340 341 342 344 346 347 348 349 350 351 352 353 354 355 356
 357 358 359 360 361 362 363 364 365 367 368 369 370 371 373 374 375 376
 377 380 381 382 383 384 386 388 390 393 394 395 396 398 399 400 402 403
 404 405 407 408 409 410 411 412 414 415 416 417 419 420 421 422 423 424
 425 426 428 429 430 431 432 433 434 436 437 438 439 440 441 442 443 444
 445 446 447 448 449 450 451 452 453 456 457 462 463 464 465 467 468 469
 470 472 473 477 478 479 480 481 482 483 485 486 487 488 490 493 494 495
 496 497 499 500 501 503 506 507 509 511 512 513 514 515 516 517 518 519
 521 522 523 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 541 542 543 544 545 547 548 549 550 551 552 553 554 556 557 558 559 567
 568 570 572 573 574 575 576 577 578 579 580 581 582 583 584 586 588 589
 590 591 592 593 594 595 597 598 599 601 602 603 604 605 606 607 608 609
 610 611 612 613 615 616 617 618 621 622 623 624 625 627 628 629 631 632
 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650
 651 653 655 656 657 658 660 661 662 663 665 666 668 669]
+ valid_idx: [  1   4  13  14  20  21  27  32  34  35  40  47  52  58  62  64  71  80
  85  87  91  95  98  99 102 105 106 121 128 130 134 138 156 159 160 161
 166 170 187 189 191 200 201 205 206 214 216 217 230 240 241 242 243 251
 252 269 270 273 276 288 295 308 313 315 330 337 339 343 345 366 372 378
 379 385 387 389 391 392 397 401 406 413 418 427 435 454 455 458 459 460
 461 466 471 474 475 476 484 489 491 492 498 502 504 505 508 510 520 524
 540 546 555 560 561 562 563 564 565 566 569 571 585 587 596 600 614 619
 620 626 630 652 654 659 664 667]
+ train / valid: [  1   4  13  14  20  21  27  32  34  35  40  47  52  58  62  64  71  80
  85  87  91  95  98  99 102 105 106 121 128 130 134 138 156 159 160 161
 166 170 187 189 191 200 201 205 206 214 216 217 230 240 241 242 243 251
 252 269 270 273 276 288 295 308 313 315 330 337 339 343 345 366 372 378
 379 385 387 389 391 392 397 401 406 413 418 427 435 454 455 458 459 460
 461 466 471 474 475 476 484 489 491 492 498 502 504 505 508 510 520 524
 540 546 555 560 561 562 563 564 565 566 569 571 585 587 596 600 614 619
 620 626 630 652 654 659 664 667]